# Generated by Django 5.0 on 2023-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='persons.city'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='persons.country'),
        ),
    ]
