# Generated by Django 5.0 on 2023-12-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_remove_person_country_person_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='additional_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='eyo', to='persons.country'),
        ),
    ]
